# Generated by Django 5.0 on 2024-04-21 19:22

import blog.models
import django.db.models.deletion
import django.utils.timezone
import django_jalali.db.models
import django_resized.forms
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('description', models.TextField(max_length=500, verbose_name='توضیحات')),
                ('email', models.EmailField(max_length=100, verbose_name='ایمیل')),
                ('phone_number', models.CharField(max_length=11, verbose_name='شماره تلفن')),
                ('subject', models.CharField(max_length=100, verbose_name='موضوع')),
            ],
            options={
                'verbose_name': 'تیکت',
                'verbose_name_plural': 'تیکت ها',
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='تاریخ تولد')),
                ('bio', models.TextField(blank=True, max_length=500, null=True, verbose_name='بایوگرافی')),
                ('bio_en', models.TextField(blank=True, max_length=500, null=True, verbose_name='بایوگرافی')),
                ('bio_fa', models.TextField(blank=True, max_length=500, null=True, verbose_name='بایوگرافی')),
                ('job', models.CharField(blank=True, max_length=500, null=True, verbose_name='شغل')),
                ('job_en', models.CharField(blank=True, max_length=500, null=True, verbose_name='شغل')),
                ('job_fa', models.CharField(blank=True, max_length=500, null=True, verbose_name='شغل')),
                ('photo', django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format=None, keep_meta=True, quality=100, scale=None, size=[500, 300], upload_to=blog.models.get_image_account, verbose_name='تصویر')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'اکانت',
                'verbose_name_plural': 'اکانت ها',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('title_en', models.CharField(max_length=200, null=True, verbose_name='عنوان')),
                ('title_fa', models.CharField(max_length=200, null=True, verbose_name='عنوان')),
                ('description', models.TextField(max_length=500, verbose_name='توضیحات')),
                ('description_en', models.TextField(max_length=500, null=True, verbose_name='توضیحات')),
                ('description_fa', models.TextField(max_length=500, null=True, verbose_name='توضیحات')),
                ('slug', models.SlugField(max_length=200, verbose_name='اسلاگ')),
                ('publish', django_jalali.db.models.jDateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ انتشار')),
                ('created', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('reading_time', models.PositiveIntegerField(verbose_name='زمان مطالعه')),
                ('status', models.CharField(choices=[('DF', 'Draft'), ('PB', 'Published'), ('RJ', 'Rejected')], default='DF', max_length=2, verbose_name='وضعیت')),
                ('category', models.CharField(choices=[('برنامه-نویسی-وب', 'برنامه نویسی وب'), ('طراحی-وبسایت', 'طراحی وبسایت'), ('برنامه-نویسی-موبایل', 'برنامه نویسی موبایل'), ('هوش-مصنوعی', 'هوش مصنوعی'), ('سایر', 'سایر')], default='سایر', max_length=20, verbose_name='دسته بندی')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_posts', to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
            ],
            options={
                'verbose_name': 'پست',
                'verbose_name_plural': 'پست ها',
                'ordering': ['-publish'],
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format=None, keep_meta=True, quality=100, scale=None, size=[500, 300], upload_to=blog.models.get_image_post, verbose_name='تصویر')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='عنوان')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='توضیحات')),
                ('created', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='blog.post', verbose_name='پست')),
            ],
            options={
                'verbose_name': 'تصویر',
                'verbose_name_plural': 'تصویر ها',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('name_en', models.CharField(max_length=100, null=True, verbose_name='نام')),
                ('name_fa', models.CharField(max_length=100, null=True, verbose_name='نام')),
                ('description', models.TextField(max_length=500, verbose_name='توضیحات')),
                ('description_en', models.TextField(max_length=500, null=True, verbose_name='توضیحات')),
                ('description_fa', models.TextField(max_length=500, null=True, verbose_name='توضیحات')),
                ('created', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('active', models.BooleanField(default=False, verbose_name='وضعیت')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.post', verbose_name='پست')),
            ],
            options={
                'verbose_name': 'کامنت',
                'verbose_name_plural': 'کامنت ها',
                'ordering': ['-created'],
            },
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-publish'], name='blog_post_publish_bb7600_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['-created'], name='blog_image_created_a116df_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['-created'], name='blog_commen_created_79f39f_idx'),
        ),
    ]
