# Generated by Django 4.2.4 on 2023-09-05 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('برنامه نویسی وب', 'برنامه نویسی وب'), ('طراحی وبسایت', 'طراحی وبسایت'), ('برنامه نویسی موبایل', 'برنامه نویسی موبایل'), ('هوش مصنوعی', 'هوش مصنوعی'), ('سایر', 'سایر')], default='سایر', max_length=20, verbose_name='دسته بندی'),
        ),
    ]
