# Generated by Django 4.2.4 on 2023-09-06 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('برنامه-نویسی-وب', 'برنامه نویسی وب'), ('طراحی-وبسایت', 'طراحی وبسایت'), ('برنامه-نویسی-موبایل', 'برنامه نویسی موبایل'), ('هوش-مصنوعی', 'هوش مصنوعی'), ('سایر', 'سایر')], default='سایر', max_length=20, verbose_name='دسته بندی'),
        ),
    ]
