# Generated by Django 4.2.4 on 2023-09-06 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_post_description_en_post_description_fa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='description_en',
            field=models.TextField(max_length=500, null=True, verbose_name='توضیحات'),
        ),
        migrations.AddField(
            model_name='comment',
            name='description_fa',
            field=models.TextField(max_length=500, null=True, verbose_name='توضیحات'),
        ),
        migrations.AddField(
            model_name='comment',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='نام'),
        ),
        migrations.AddField(
            model_name='comment',
            name='name_fa',
            field=models.CharField(max_length=100, null=True, verbose_name='نام'),
        ),
    ]
